Error Handling Update
In order to allow 3rd Party applications to interact better in case of
an Error, a new Callback Method has been added:
onError:  function(errormsg){ console.log('onError:'+errormsg) }

Additionally in this update the two sample php files have been updated
to ensure:
- Write Access check to the directory
- Proper feedback if the File is larger then allowed for upload